baseURL = 'https://int-main-void.github.io/'
languageCode = 'en-us'
title = 'developing thoughts'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
recent_posts_number = 3
body_classes = "avenir bg-near-white"
post_content_classes = "avenir bg-near-white"

